#!/usr/bin/env python3

from Bio.PDB.PDBParser import PDBParser
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import sys, math
from fft import init_grid
import pdb_resdepth

def read_pdb(filename):
    """
        READs PDB FILE with BioPython
        INPUT:
            PDB path/filename(str)
        OUTPUT:
            structure(BioPython Structure object)
    """
    parser = PDBParser(PERMISSIVE=1)
    pdbid = filename.split(".")[0]
    structure = parser.get_structure(pdbid, filename)
    return(structure)

def pdb_data_extractor(structure, chainId, depth_dict, depthCutoff):
    """
    COMPUTES RESIDUE POSITIONS AND DEPTH from Structure object
    INPUT:
        structure(BioPython Structure object)
        chainId(str) chain for which to compute residue positions and depth
        depth_dict(dict) Dictionary of residue depth generated by calculate_resdepth()
        depthCutoff(float) depth Cutoff for surface determination
    OUPUT:
        df(pandas dataframe) positions of CB/CA and RESIDUE DEPTH (to add)
            x(list) x position of residues (CA or CB)
            y(list) y position of residues (CA or CB)
            z(list) z position of residues (CA or CB)
            resdepth(list) residue depth, 1 if at surface, else -1
    """
    amino = [
        "ALA",
        "ILE",
        "LEU",
        "PRO",
        "VAL",
        "PHE",
        "TRP",
        "TYR",
        "ASP",
        "GLU",
        "ARG",
        "HIS",
        "LYS",
        "SER",
        "THR",
        "CYS",
        "MET",
        "ASN",
        "GLN"]
    x = []
    y = []
    z = []
    resname = []
    resdepth = []
    for model in structure:
        for chain in model:
            if chain.get_id() == chainId :
                for residue in chain:
                    if "GLY" in residue.get_resname():
                        resdepth.append(pdb_resdepth.resdepth_to_fft(residue = residue, cutoff = depthCutoff, mydict = depth_dict))
                        resname.append(residue.get_resname()+str(residue.get_full_id()[3][1])+residue.get_full_id()[2])
                        for atom in residue:
                            if atom.get_name() == "CA":
                                posx = atom.get_coord()[0]
                                x.append(posx)
                                posy = atom.get_coord()[1]
                                y.append(posy)
                                posz = atom.get_coord()[2]
                                z.append(posz)

                    elif residue.get_resname() in amino:
                        resdepth.append(pdb_resdepth.resdepth_to_fft(residue = residue, cutoff = depthCutoff, mydict = depth_dict))
                        resname.append(residue.get_resname()+str(residue.get_full_id()[3][1])+residue.get_full_id()[2])
                        for atom in residue:
                            if atom.get_name() == "CB":
                                posx = atom.get_coord()[0]
                                x.append(posx)
                                posy = atom.get_coord()[1]
                                y.append(posy)
                                posz = atom.get_coord()[2]
                                z.append(posz)

    df = pd.DataFrame(x, columns = ["x"], index = resname)
    df["y"] = y
    df["z"] = z
    df["resdepth"] = resdepth
    return(df)









def pdb_fft(filename, recepChain, ligChain, depth_dict, depthCutoff):
    """
        READs PDB FILE AND COMPUTES RESIDUE POSITIONS AND DEPTH
        INPUT :
            PDB path/filename(str)
            recepChain(list) list of receptors chain(str)
            ligChain(list) list of ligand chain(str)
            depth_dict(dict) Dictionary of residue depth generated by calculate_resdepth()
            depthCutoff(float) depth Cutoff for surface determination

        OUTPUT :
            list of pandas dataframe (1 for receptor, 1 for ligand): positions of CB/CA and RESIDUE DEPTH
                x(list) x position of residues (CA or CB)
                y(list) y position of residues (CA or CB)
                z(list) z position of residues (CA or CB)
                resdepth(list) residue depth, 1 if at surface, else -1
    """


    structure = read_pdb(filename=filename)
    receptor = []
    ligand = []
    for model in structure:
        for chain in model:
            if chain.get_id() in recepChain:
                receptor.append(pdb_data_extractor(structure = structure, chainId = chain.get_id(), depth_dict = depth_dict, depthCutoff = depthCutoff))
            elif chain.get_id() in ligChain:
                ligand.append(pdb_data_extractor(structure = structure, chainId = chain.get_id(), depth_dict = depth_dict, depthCutoff = depthCutoff))
    receptorData = pd.concat(receptor)
    ligandData = pd.concat(ligand)
    return([receptorData, ligandData])




def get_grid_parameters(x, y, z):
    """
        COMPUTES GRID PARAMETERS FOR FFT
        INPUT:
            x(list) x coordinates of residues
            y(list) y coordinates of residues
            z(list) z coordinates of residues
        OUTPUT:
            nb_cells(int) number of grid cells
            Lmin(int) min X|Y|Z positions
            Lmax(int) max X|Y|Z positions
    """

    Lmax = max(max(x), max(y), max(z))
    Lmin = min(min(x), min(y), min(z))
    L = math.ceil(Lmax) - math.floor(Lmin)
    parameters = (L, Lmin, Lmax)
    return(parameters)


def scale_coords(df, grid_parameters, margin = 5):
    """
    SCALES RESIDUE COORDINATES
    INPUT:
        df(pandas dataframe) output of read_pdb() function
        grid_parameters(tuple) output of get_grid_parameters() function
    OUTPUT:
        df(pandas dataframe) scaled output of read_pdb()
    """
    df.iloc[:,0] = np.interp(df.iloc[:,0], [grid_parameters[1], grid_parameters[2]], [
                          0+margin, grid_parameters[0] - margin])
    df.iloc[:,1] = np.interp(df.iloc[:,1], [grid_parameters[1], grid_parameters[2]], [
                          0+margin, grid_parameters[0] - margin])
    df.iloc[:,2] = np.interp(df.iloc[:,2], [grid_parameters[1], grid_parameters[2]], [
                          0+margin, grid_parameters[0] - margin])
    return(df)



if __name__ == "__main__":
    resolution = 9.2
    depthCutoff = 4
    recepChain = ["A","B"]
    ligChain = ["C","D"]
    # filename = "./2ZA4.pdb"
    filename = sys.argv[1]
    pdb_structure = read_pdb(filename)
    depth_dict = pdb_resdepth.calculate_resdepth(structure=pdb_structure, pdb_filename=filename)

    data = pdb_fft(filename = filename, recepChain = recepChain, ligChain = ligChain, depth_dict = depth_dict, depthCutoff = depthCutoff)
    receptor = data[0]
    ligand = data[1]
    # receptor
    rec_grid_parameters=get_grid_parameters(x=receptor.iloc[:,0], y=receptor.iloc[:,1], z=receptor.iloc[:,2])
    rec_coords = scale_coords(receptor, grid_parameters= rec_grid_parameters)
    rec_mygrid = init_grid(N=rec_grid_parameters[0], mesh_size = resolution)
    print(rec_grid_parameters)
    fig = plt.figure()
    ax = fig.gca(projection='3d')
    ax.scatter(xs=rec_mygrid.iloc[:,0], ys=rec_mygrid.iloc[:,1], zs=rec_mygrid.iloc[:,2], c = "blue", alpha = resolution/100)
    ax.scatter(xs=rec_coords.iloc[:,0], ys=rec_coords.iloc[:,1], zs=rec_coords.iloc[:,2], c = "red")
    plt.show()

    #ligand

    lig_grid_parameters=get_grid_parameters(x=ligand.iloc[:,0], y=ligand.iloc[:,1], z=ligand.iloc[:,2])
    lig_coords = scale_coords(ligand, grid_parameters= lig_grid_parameters)
    lig_mygrid = init_grid(N=lig_grid_parameters[0], mesh_size = resolution)
    print(lig_grid_parameters)
    fig = plt.figure()
    ax = fig.gca(projection='3d')
    ax.scatter(xs=lig_mygrid.iloc[:,0], ys=lig_mygrid.iloc[:,1], zs=lig_mygrid.iloc[:,2], c = "blue", alpha = resolution/100)
    ax.scatter(xs=lig_coords.iloc[:,0], ys=lig_coords.iloc[:,1], zs=lig_coords.iloc[:,2], c = "green")
    plt.show()
